import Link from 'next/link';
import { notFound } from 'next/navigation';
import { projects } from '../../data/projects';
import ProjectVisual from '../../components/ProjectVisual';
export function generateStaticParams() { return projects.map(project => ({ slug: project.slug })); }
export function generateMetadata({ params }: { params: { slug: string } }) { const project = projects.find(p => p.slug === params.slug); return { title: project?.title ?? 'Project not found', description: project?.summary }; }
export default function ProjectPage({ params }: { params: { slug: string } }) {
  const project = projects.find(p => p.slug === params.slug);
  if (!project) notFound();
  const nextProject = projects[(projects.indexOf(project) + 1) % projects.length];
  return <article className="case-study section-wrap"><Link className="back-link" href="/portfolio">← All work</Link><header className="case-header"><span className="eyebrow">{project.organization}</span><h1>{project.title}</h1><p>{project.summary}</p><div className="category-tags">{project.categories.map(category => <span key={category}>{category}</span>)}</div></header><ProjectVisual project={project}/><dl className="case-facts"><div><dt>CONTEXT</dt><dd>{project.context}</dd></div><div><dt>MY CONTRIBUTION</dt><dd>{project.contribution}</dd></div><div><dt>TOOLS & METHODS</dt><dd>{project.tools.join(' · ')}</dd></div></dl><div className="case-layout"><nav aria-label="Case study sections"><span className="eyebrow">IN THIS STORY</span><a href="#problem">01 / The question</a><a href="#approach">02 / The approach</a><a href="#build">03 / The work</a><a href="#learning">04 / The reflection</a></nav><div className="case-body"><section id="problem"><span className="eyebrow">01 / THE QUESTION</span><h2>Where it started.</h2><p>{project.problem}</p></section><section id="approach"><span className="eyebrow">02 / THE APPROACH</span><h2>Working through it.</h2><ol className="approach-list">{project.approach.map((step, i) => <li key={step}><span>0{i + 1}</span><p>{step}</p></li>)}</ol></section><section id="build"><span className="eyebrow">03 / THE WORK</span><h2>From thinking to doing.</h2><p>{project.build}</p>{project.github && <a className="button-link" href={project.github} target="_blank" rel="noreferrer">Explore the code ↗</a>}</section><section id="learning"><span className="eyebrow">04 / THE REFLECTION</span><h2>What comes next.</h2><p>{project.learning}</p></section><details className="case-notebook"><summary>Case study notebook <span>In progress +</span></summary><p>This project’s write-up is still growing. The next pieces to document:</p><ul>{project.next.map(item => <li key={item}>{item}</li>)}</ul></details></div></div><Link className="next-project" href={`/portfolio/${nextProject.slug}`}><span className="eyebrow">KEEP EXPLORING</span><strong>{nextProject.title} <span>→</span></strong></Link></article>;
}
